networks:
  shared:
    external: true

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    networks:
      - shared
    environment:
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    # ports:
    #   - "8085:3000"
    volumes:
      - "grafana_storage:/var/lib/grafana"
volumes:
  grafana_storage: {}
