- name: Homelab Setup
  hosts: myhosts
  gather_facts: true
  become: true
  roles:
    # Core
    - { role: common_setup, tags: [core, common_setup] }
    - { role: docker, tags: [core, docker] }

    # Networking Stack
    - { role: traefik, tags: [networking, traefik] }
    - { role: adguardhome, tags: [networking, adguardhome] }
    - { role: gluetun, tags: [networking, gluetun] }
    - { role: dockhand, tags: [networking, dockhand] }

    # Cloud services
    - { role: nextcloud, tags: [cloud, nextcloud] }

    # Observability
    - { role: grafana, tags: [observability, grafana] }

    # Programming Tools
    - { role: forgejo, tags: [dev, forgejo] }

    # Databases
    - { role: mongodb, tags: [databases, mongodb] }

    # Misc
    - { role: searxng, tags: [misc, searxng] }
