- name: Homelab Setup
  hosts: myhosts
  gather_facts: true
  become: true
  roles:
    # Core
    - common_setup
    - docker

    # Networking Stack
    - traefik
    - adguardhome
    - gluetun

    # Observability
    - grafana

    # Programming Tools
    - forgejo

    # Databases
    - mongodb

    # Misc
    - searxng
