networks:
  shared:
    external: true

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    networks:
      - shared
    ports:
      - "53:53/tcp" # DNS
      - "53:53/udp" # DNS
      # - "3001:3000/tcp" #Setup wizard port 
      # - "8082:80/tcp" # Main admin web interface port
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=shared"
      - "traefik.http.routers.adguard.entrypoints=https"
      - "traefik.http.routers.adguard.rule=Host(`adguard.toot-net.com`)"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.http.routers.adguard.tls.certresolver=cloudflare"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"
